# Generated by Django 5.1.2 on 2024-10-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='content',
            field=models.TextField(default='Default content here'),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='package_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='serial_image',
            field=models.ImageField(blank=True, null=True, upload_to='serial_images/'),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='recipient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
